-- Scenario 1: University Library Book Loans
-- Open in pgAdmin Query Tool on your practice database and press F5 (Execute).
-- RAISE NOTICE messages appear in the Messages tab. Query results appear in Data Output.
-- Rename this file to scenario_1_YOUR_STUDENT_NUMBER.sql before submitting.

DROP SCHEMA IF EXISTS library_lab CASCADE;
CREATE SCHEMA library_lab;
SET search_path TO library_lab, public;

CREATE TABLE books (
    book_id integer PRIMARY KEY,
    book_title text NOT NULL,
    available_copies integer NOT NULL CHECK (available_copies >= 0)
);

CREATE TABLE book_loans (
    loan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id integer NOT NULL REFERENCES books(book_id),
    student_number text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);

INSERT INTO books (book_id, book_title, available_copies)
VALUES (1, 'Database Systems', 5),
       (2, 'Python Programming', 2),
       (3, 'Computer Networks', 4);

SELECT * FROM books ORDER BY book_id;
SET search_path TO library_lab, public;
DO $$
DECLARE
    v_copies integer;
BEGIN
    SELECT available_copies INTO v_copies
    FROM books WHERE book_id = 2;

    IF v_copies = 0 THEN
        RAISE NOTICE 'Python Programming unavailable';
    ELSIF v_copies <= 2 THEN
        RAISE NOTICE 'Python Programming low: % remaining', v_copies;
    ELSE
        RAISE NOTICE 'Python Programming sufficiently stocked: % remaining', v_copies;
    END IF;
END;
$$ LANGUAGE plpgsql;
DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Overdue reminder %', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_shelf IN 1..3 LOOP
        RAISE NOTICE 'Shelf number %', v_shelf;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE PROCEDURE library_lab.borrow_book(
    p_book_id integer,
    p_student_number text,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_loan_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_copies INTO v_available
    FROM library_lab.books
    WHERE book_id = p_book_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Book % does not exist', p_book_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_available;
        RETURN;
    END IF;

    UPDATE library_lab.books
    SET available_copies = available_copies - p_quantity
    WHERE book_id = p_book_id;

    INSERT INTO library_lab.book_loans
        (book_id, student_number, quantity, status)
    VALUES (p_book_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING loan_id INTO v_loan_id;

    RAISE NOTICE 'Loan % created for student %',
        v_loan_id, p_student_number;
END;
$$;
CALL library_lab.borrow_book(1, 'STU001', 2);
CALL library_lab.borrow_book(2, 'STU002', 1);
CALL library_lab.borrow_book(2, 'STU003', 10);

SELECT book_id, book_title, available_copies
FROM library_lab.books ORDER BY book_id;

SELECT loan_id, book_id, student_number, quantity, status
FROM library_lab.book_loans ORDER BY loan_id;
CREATE OR REPLACE PROCEDURE library_lab.return_book(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_book_id integer;
    v_quantity integer;
BEGIN
    SELECT book_id, quantity
    INTO v_book_id, v_quantity
    FROM library_lab.book_loans
    WHERE loan_id = p_loan_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active loan with ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE library_lab.book_loans
    SET status = 'RETURNED' WHERE loan_id = p_loan_id;

    UPDATE library_lab.books
    SET available_copies = available_copies + v_quantity
    WHERE book_id = v_book_id;

    RAISE NOTICE 'Loan % returned; % copies restored',
        p_loan_id, v_quantity;
END;
$$;

CALL library_lab.return_book(1);
CALL library_lab.return_book(1);

SELECT * FROM library_lab.books ORDER BY book_id;
SELECT loan_id, status FROM library_lab.book_loans ORDER BY loan_id;
CREATE OR REPLACE PROCEDURE library_lab.show_low_copies()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT book_title, available_copies
        FROM library_lab.books
        WHERE available_copies <= 2
        ORDER BY book_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Few copies remaining: % (% remaining)',
            v_item.book_title, v_item.available_copies;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL library_lab.show_low_copies();
DO $$
BEGIN
    CALL library_lab.borrow_book(3, 'STU004', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
SELECT book_id, book_title, available_copies
FROM library_lab.books ORDER BY book_id;

SELECT loan_id, book_id, student_number, quantity, status
FROM library_lab.book_loans ORDER BY loan_id;
