-- Scenario 3: Student Hostel Room Allocation
-- Open in pgAdmin Query Tool on your practice database and press F5 (Execute).
-- RAISE NOTICE messages appear in the Messages tab. Query results appear in Data Output.
-- Rename this file to scenario_3_YOUR_STUDENT_NUMBER.sql before submitting.

DROP SCHEMA IF EXISTS hostel_lab CASCADE;
CREATE SCHEMA hostel_lab;
SET search_path TO hostel_lab, public;

CREATE TABLE hostel_rooms (
    room_id integer PRIMARY KEY,
    room_number text NOT NULL,
    available_spaces integer NOT NULL CHECK (available_spaces >= 0)
);

CREATE TABLE allocations (
    allocation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL REFERENCES hostel_rooms(room_id),
    student_number text NOT NULL,
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CHECKED_OUT'))
);

INSERT INTO hostel_rooms (room_id, room_number, available_spaces)
VALUES (1, 'A101', 4),
       (2, 'B202', 1),
       (3, 'C303', 3);

SELECT * FROM hostel_rooms ORDER BY room_id;
SET search_path TO hostel_lab, public;
DO $$
DECLARE
    v_spaces integer;
BEGIN
    SELECT available_spaces INTO v_spaces
    FROM hostel_rooms WHERE room_id = 2;

    IF v_spaces = 0 THEN
        RAISE NOTICE 'Room B202 full';
    ELSIF v_spaces = 1 THEN
        RAISE NOTICE 'Room B202 nearly full: one space left';
    ELSE
        RAISE NOTICE 'Room B202 has several spaces: % available', v_spaces;
    END IF;
END;
$$ LANGUAGE plpgsql;
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Inspection day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Room check %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE PROCEDURE hostel_lab.allocate_room(
    p_room_id integer,
    p_student_number text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_allocation_id integer;
BEGIN
    IF p_student_number IS NULL OR btrim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student number must not be blank';
    END IF;

    SELECT available_spaces INTO v_available
    FROM hostel_lab.hostel_rooms
    WHERE room_id = p_room_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Room % does not exist', p_room_id;
        RETURN;
    ELSIF v_available < 1 THEN
        RAISE NOTICE 'Room full: no spaces available';
        RETURN;
    END IF;

    UPDATE hostel_lab.hostel_rooms
    SET available_spaces = available_spaces - 1
    WHERE room_id = p_room_id;

    INSERT INTO hostel_lab.allocations
        (room_id, student_number, status)
    VALUES (p_room_id, p_student_number, 'ACTIVE')
    RETURNING allocation_id INTO v_allocation_id;

    RAISE NOTICE 'Allocation % created for student %',
        v_allocation_id, p_student_number;
END;
$$;
CALL hostel_lab.allocate_room(1, 'STU101');
CALL hostel_lab.allocate_room(2, 'STU102');
CALL hostel_lab.allocate_room(2, 'STU103');

SELECT room_id, room_number, available_spaces
FROM hostel_lab.hostel_rooms ORDER BY room_id;

SELECT allocation_id, room_id, student_number, status
FROM hostel_lab.allocations ORDER BY allocation_id;
CREATE OR REPLACE PROCEDURE hostel_lab.check_out(p_allocation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_room_id integer;
BEGIN
    SELECT room_id
    INTO v_room_id
    FROM hostel_lab.allocations
    WHERE allocation_id = p_allocation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active allocation with ID %', p_allocation_id;
        RETURN;
    END IF;

    UPDATE hostel_lab.allocations
    SET status = 'CHECKED_OUT' WHERE allocation_id = p_allocation_id;

    UPDATE hostel_lab.hostel_rooms
    SET available_spaces = available_spaces + 1
    WHERE room_id = v_room_id;

    RAISE NOTICE 'Allocation % checked out; one space released',
        p_allocation_id;
END;
$$;

CALL hostel_lab.check_out(1);
CALL hostel_lab.check_out(1);

SELECT * FROM hostel_lab.hostel_rooms ORDER BY room_id;
SELECT allocation_id, status FROM hostel_lab.allocations ORDER BY allocation_id;
CREATE OR REPLACE PROCEDURE hostel_lab.show_full_or_nearly_full()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_full CURSOR FOR
        SELECT room_number, available_spaces
        FROM hostel_lab.hostel_rooms
        WHERE available_spaces <= 1
        ORDER BY room_id;
BEGIN
    OPEN c_full;
    LOOP
        FETCH c_full INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full or nearly full room: % (% spaces left)',
            v_item.room_number, v_item.available_spaces;
    END LOOP;
    CLOSE c_full;
END;
$$;

CALL hostel_lab.show_full_or_nearly_full();
DO $$
BEGIN
    CALL hostel_lab.allocate_room(3, '');
EXCEPTION WHEN others THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
SELECT room_id, room_number, available_spaces
FROM hostel_lab.hostel_rooms ORDER BY room_id;

SELECT allocation_id, room_id, student_number, status
FROM hostel_lab.allocations ORDER BY allocation_id;
