-- Scenario 4: Campus Clinic Medicine Dispensing
-- Open in pgAdmin Query Tool on your practice database and press F5 (Execute).
-- RAISE NOTICE messages appear in the Messages tab. Query results appear in Data Output.
-- Rename this file to scenario_4_YOUR_STUDENT_NUMBER.sql before submitting.

DROP SCHEMA IF EXISTS clinic_lab CASCADE;
CREATE SCHEMA clinic_lab;
SET search_path TO clinic_lab, public;

CREATE TABLE medicines (
    medicine_id integer PRIMARY KEY,
    medicine_name text NOT NULL,
    stock_quantity integer NOT NULL CHECK (stock_quantity >= 0)
);

CREATE TABLE dispensing_records (
    record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id integer NOT NULL REFERENCES medicines(medicine_id),
    student_number text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'REVERSED'))
);

INSERT INTO medicines (medicine_id, medicine_name, stock_quantity)
VALUES (1, 'Paracetamol', 50),
       (2, 'Ibuprofen', 5),
       (3, 'Amoxicillin', 20);

SELECT * FROM medicines ORDER BY medicine_id;
SET search_path TO clinic_lab, public;
DO $$
DECLARE
    v_stock integer;
BEGIN
    SELECT stock_quantity INTO v_stock
    FROM medicines WHERE medicine_id = 2;

    IF v_stock = 0 THEN
        RAISE NOTICE 'Ibuprofen out of stock';
    ELSIF v_stock <= 5 THEN
        RAISE NOTICE 'Ibuprofen low: % remaining', v_stock;
    ELSE
        RAISE NOTICE 'Ibuprofen sufficiently stocked: % remaining', v_stock;
    END IF;
END;
$$ LANGUAGE plpgsql;
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Stock review day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_shelf IN 1..3 LOOP
        RAISE NOTICE 'Shelf inspection %', v_shelf;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE PROCEDURE clinic_lab.dispense_medicine(
    p_medicine_id integer,
    p_student_number text,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_record_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT stock_quantity INTO v_available
    FROM clinic_lab.medicines
    WHERE medicine_id = p_medicine_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Medicine % does not exist', p_medicine_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_available;
        RETURN;
    END IF;

    UPDATE clinic_lab.medicines
    SET stock_quantity = stock_quantity - p_quantity
    WHERE medicine_id = p_medicine_id;

    INSERT INTO clinic_lab.dispensing_records
        (medicine_id, student_number, quantity, status)
    VALUES (p_medicine_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING record_id INTO v_record_id;

    RAISE NOTICE 'Dispensing record % created for student %',
        v_record_id, p_student_number;
END;
$$;
CALL clinic_lab.dispense_medicine(1, 'STU201', 10);
CALL clinic_lab.dispense_medicine(2, 'STU202', 3);
CALL clinic_lab.dispense_medicine(2, 'STU203', 20);

SELECT medicine_id, medicine_name, stock_quantity
FROM clinic_lab.medicines ORDER BY medicine_id;

SELECT record_id, medicine_id, student_number, quantity, status
FROM clinic_lab.dispensing_records ORDER BY record_id;
CREATE OR REPLACE PROCEDURE clinic_lab.reverse_dispensing(p_record_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_medicine_id integer;
    v_quantity integer;
BEGIN
    SELECT medicine_id, quantity
    INTO v_medicine_id, v_quantity
    FROM clinic_lab.dispensing_records
    WHERE record_id = p_record_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active dispensing record with ID %', p_record_id;
        RETURN;
    END IF;

    UPDATE clinic_lab.dispensing_records
    SET status = 'REVERSED' WHERE record_id = p_record_id;

    UPDATE clinic_lab.medicines
    SET stock_quantity = stock_quantity + v_quantity
    WHERE medicine_id = v_medicine_id;

    RAISE NOTICE 'Dispensing % reversed; % units restored',
        p_record_id, v_quantity;
END;
$$;

CALL clinic_lab.reverse_dispensing(1);
CALL clinic_lab.reverse_dispensing(1);

SELECT * FROM clinic_lab.medicines ORDER BY medicine_id;
SELECT record_id, status FROM clinic_lab.dispensing_records ORDER BY record_id;
CREATE OR REPLACE PROCEDURE clinic_lab.show_low_stock()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT medicine_name, stock_quantity
        FROM clinic_lab.medicines
        WHERE stock_quantity <= 5
        ORDER BY medicine_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Below low-stock threshold: % (% remaining)',
            v_item.medicine_name, v_item.stock_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL clinic_lab.show_low_stock();
DO $$
BEGIN
    CALL clinic_lab.dispense_medicine(3, 'STU204', -1);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
SELECT medicine_id, medicine_name, stock_quantity
FROM clinic_lab.medicines ORDER BY medicine_id;

SELECT record_id, medicine_id, student_number, quantity, status
FROM clinic_lab.dispensing_records ORDER BY record_id;
