-- Scenario 2: Computer Laboratory Reservations
-- Open in pgAdmin Query Tool on your practice database and press F5 (Execute).
-- RAISE NOTICE messages appear in the Messages tab. Query results appear in Data Output.
-- Rename this file to scenario_2_YOUR_STUDENT_NUMBER.sql before submitting.

DROP SCHEMA IF EXISTS lab_reservations CASCADE;
CREATE SCHEMA lab_reservations;
SET search_path TO lab_reservations, public;

CREATE TABLE lab_sessions (
    session_id integer PRIMARY KEY,
    session_name text NOT NULL,
    available_workstations integer NOT NULL CHECK (available_workstations >= 0)
);

CREATE TABLE reservations (
    reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer text NOT NULL,
    workstations integer NOT NULL CHECK (workstations > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES (1, 'Programming Lab A', 8),
       (2, 'Networking Lab', 2),
       (3, 'Database Lab', 5);

SELECT * FROM lab_sessions ORDER BY session_id;
SET search_path TO lab_reservations, public;
DO $$
DECLARE
    v_workstations integer;
BEGIN
    SELECT available_workstations INTO v_workstations
    FROM lab_sessions WHERE session_id = 2;

    IF v_workstations = 0 THEN
        RAISE NOTICE 'Networking Lab full';
    ELSIF v_workstations <= 2 THEN
        RAISE NOTICE 'Networking Lab nearly full: % workstations left', v_workstations;
    ELSE
        RAISE NOTICE 'Networking Lab has enough workstations: % available', v_workstations;
    END IF;
END;
$$ LANGUAGE plpgsql;
DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Session prep reminder %', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Workstation check %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE PROCEDURE lab_reservations.reserve_workstations(
    p_session_id integer,
    p_lecturer text,
    p_workstations integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_reservation_id integer;
BEGIN
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Workstations requested must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_workstations INTO v_available
    FROM lab_reservations.lab_sessions
    WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Insufficient workstations: only % available', v_available;
        RETURN;
    END IF;

    UPDATE lab_reservations.lab_sessions
    SET available_workstations = available_workstations - p_workstations
    WHERE session_id = p_session_id;

    INSERT INTO lab_reservations.reservations
        (session_id, lecturer, workstations, status)
    VALUES (p_session_id, p_lecturer, p_workstations, 'ACTIVE')
    RETURNING reservation_id INTO v_reservation_id;

    RAISE NOTICE 'Reservation % created for lecturer %',
        v_reservation_id, p_lecturer;
END;
$$;
CALL lab_reservations.reserve_workstations(1, 'Dr Smith', 3);
CALL lab_reservations.reserve_workstations(2, 'Prof Jones', 1);
CALL lab_reservations.reserve_workstations(2, 'Dr Brown', 10);

SELECT session_id, session_name, available_workstations
FROM lab_reservations.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM lab_reservations.reservations ORDER BY reservation_id;
CREATE OR REPLACE PROCEDURE lab_reservations.cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_session_id integer;
    v_workstations integer;
BEGIN
    SELECT session_id, workstations
    INTO v_session_id, v_workstations
    FROM lab_reservations.reservations
    WHERE reservation_id = p_reservation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE lab_reservations.reservations
    SET status = 'CANCELLED' WHERE reservation_id = p_reservation_id;

    UPDATE lab_reservations.lab_sessions
    SET available_workstations = available_workstations + v_workstations
    WHERE session_id = v_session_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released',
        p_reservation_id, v_workstations;
END;
$$;

CALL lab_reservations.cancel_reservation(1);
CALL lab_reservations.cancel_reservation(1);

SELECT * FROM lab_reservations.lab_sessions ORDER BY session_id;
SELECT reservation_id, status FROM lab_reservations.reservations ORDER BY reservation_id;
CREATE OR REPLACE PROCEDURE lab_reservations.show_few_workstations()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_few CURSOR FOR
        SELECT session_name, available_workstations
        FROM lab_reservations.lab_sessions
        WHERE available_workstations <= 2
        ORDER BY session_id;
BEGIN
    OPEN c_few;
    LOOP
        FETCH c_few INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Few workstations left: % (% remaining)',
            v_item.session_name, v_item.available_workstations;
    END LOOP;
    CLOSE c_few;
END;
$$;

CALL lab_reservations.show_few_workstations();
DO $$
BEGIN
    CALL lab_reservations.reserve_workstations(3, 'Dr White', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
SELECT session_id, session_name, available_workstations
FROM lab_reservations.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM lab_reservations.reservations ORDER BY reservation_id;
